#
# ~/.shellrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export GPG_TTY="$(tty)"

stty -ixon ## disables ctrl-s and ctrl-q

alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
