#!/bin/sh

## The following line can break a vanilla Gentoo install
#dbus-update-activation-environment DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

slstatus &

## For X11 forwarding over ssh
#ssh-agent dwm

exec dbus-launch dwm > "${HOME}/.dwm.log"

