#!/bin/sh

## The following line can break a vanilla Gentoo install
#dbus-update-activation-environment DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

pkill mpd
mpd

xautolock -time 10 -locker slock &

slstatus &

exec dbus-launch dwm > "${HOME}/.dwm.log"
