#!/bin/sh

XDG_RUNTIME_DIR=/home/mikolaj/.run
PULSE_RUNTIME_PATH="${XDG_RUNTIME_DIR}/pulse"

PULSE_ENV="env PULSE_RUNTIME_PATH=${PULSE_RUNTIME_PATH} XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}"
PULSE="${PULSE_ENV} pulseaudio"
