#!/bin/sh

. ./common.sh

while [ ! -d /run/user/$(id -u)/ ]; do
	sleep 2
done

${PULSE} --use-pid-file=true --start

# wait for pulseaudio to exit by reading from /dev/null until pulseaudio's
# pid gets killed
exec tail --pid="$(cat ${PULSE_RUNTIME_PATH}/pid)" -f /dev/null
