#!/bin/sh

SYSRESOURCES="/etc/X11/xinit/.Xresources"
SYSMODMAP="/etc/X11/xinit/.Xmodmap"
USERRESOURCES="${HOME}/.Xresources"
USERMODMAP="${HOME}/.Xmodmap"

[ -f "${SYSRESOURCES}" ] && xrdb -merge "${SYSRESOURCES}"
[ -f "${SYSMODMAP}" ] && xmodmap "${SYSMODMAP}"

[ -f "${USERRESOURCES}" ] && xrdb -merge "${USERRESOURCES}"
[ -f "${USERMODMAP}" ] && xmodmap "${USERMODMAP}"

## start any necessary programs
if [ -d "/etc/X11/xinit/xinitrc.d" ]; then
	for F in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$F" ] && . "$F"
	done
fi

